#server:
#  port: 80
#
#scs.scs.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN6Z8txjn4k1uh1/NMMOZqx4sa+EQDG61rOsbIxc+aEuANRyZC45oOkAfi28lOUCe2RYT2yB2AwI8ZgK1QSemSECAwEAAQ==
#spring:
#  profiles:
#    active: dev
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  datasource:
#      url: jdbc:mysql://mysql2.test.yiyaowang.com:3306/yc_open?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#      username: yc_open
#      password: tzwHeXmztRkr1KhqAwhZfzfAH16WX0a16PlRuD+VynG7Dz986x3G0Kz4aVL5WJHLPI9JK5fNJByGzUxR+CF7Rw==
#      driver-class-name: com.mysql.jdbc.Driver
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,slf4j,config
#        connection-properties: stat.mergeSql=true;stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${scs.scs.key}
#  application:
#    name: b2b-sps-web
#  freemarker:
#    request-context-attribute: req  #req访问request
#    suffix: .ftl  #后缀名
#    content-type: text/html
#    enabled: true
#    cache: false #缓存配置
##    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
#    charset: UTF-8 #编码格式
#    settings:
#        number_format: '0.##'   #数字格式化，无小数点
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mapper:
  not-empty: true
  mappers: com.yao.sps.MyMapper
  identity: MYSQL
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true  ##开启驼峰

##logging:
##  path: logs/
#signature:
#  posX : 43000
#  posY : 7000
#  totalCount : 100
